name: 'Contributor Map'
description: 'Generate an SVG map showing countries with the most contributions to the repository'
branding:
  icon: 'map'
  color: 'green'
inputs:
  repository:
    description: 'Name of the repository for which generate the contributor map'
    required: false
    default: ${{ github.repository }}
  output:
    description: 'Name of the generated map file'
    required: false
    default: 'contributor-map.svg'
  palette:
    description: 'A list of comma-separated hex triplets to customize the appearance of the map'
    required: false

runs:
  using: composite
  steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate map
      uses: docker://ghcr.io/tunaitis/contributor-map:dev
      with:
        repository: ${{ inputs.repository }}
        token: ${{ github.token }}
        output: ${{ inputs.output }}
        palette: ${{ inputs.palette }}

    - name: Commit the generated file back to the repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
